### ISSUE TITLE
甘特图增加周末颜色显示

### ISSUE THREAD

**Issue by xfworld** [limodou/uli-gantt#1]
hi,Eric,我收到你的回信了,然后,我想在甘特图给每个周末加上特效显示,这个有没有简单的修改办法

**Comment by limodou** [comment]
这个要使用d3来画，而且只对日的视图有用，因为周和月的视图看不到周末。所以我感觉用处不是很大。另外就是怎么画的问题。不知你能否帮助我们改进一下呢？

**Comment by xfworld** [comment]
没用过d3阿,我看看先...

**Comment by limodou** [comment]
我这边到是也在改。

**Comment by limodou** [comment]
完成了 a6da85554190e909185c84b8eb29682cd1e8a309
