### ISSUE TITLE
uliGantt.js fix bug

### ISSUE THREAD

**Issue by xfworld** [limodou/uli-gantt#2]
![image](https://f.cloud.github.com/assets/5020771/2382512/5ac233fe-a8e6-11e3-97a0-cb7a70ffd91c.png)
 var settings = $.extend(true, grid_settings,this.grid_opts);

提交的版本中grid_settings和this.grid_opts合并的参数位置是相反的,会导致url和expandURL全部被合并为url,expandURL原值会丢失

**Comment by limodou** [comment]
这样是当expandURL没有传值时，就使用缺省的url的值，如果传了值，则还是会用你的值进行替換。这个值就应该是一个字符串，只会替換，不会合并啊。

**Comment by xfworld** [comment]
你试试原代码就知道了. 加载父节点和获取子节点分别是两个url,用原来版本的,会导致两个url都一样.

**Comment by limodou** [comment]
017c8999ffa25ea0f89139ba0649bfc17b6ed134

**Comment by limodou** [comment]
Fixed
